on: push
name: Push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: docker://culturehq/actions-yarn:latest
      with:
        args: install
    - name: Lint
      uses: docker://culturehq/actions-yarn:latest
      with:
        args: lint
